name: motorway-takehome-backend

on:
  push:
    branches:
      - master

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["18.4"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install modules
        run: npm ci
      - name: lint
        run: npm run lint
      - name: Create .env.test
        run: cp .env.example .env.test
      - name: tests
        run: npm test
